service: lambda-typescript-template
frameworkVersion: '3'

package:
  individually: true
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, 'development'}
  stackName: template-service # @NOTE: update to the service name
  deploymentMethod: direct
  deploymentBucket: acema-serverless
  versionFunctions: false
  environment:
    NODE_ENV: ${opt:stage, 'development'}
  httpApi:
    cors: true
   # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "dynamodb:GetItem"
  #     Resource:
  #       Fn::GetAtt:
  #         - UserTable
  #         - Arn

functions:
  - ${file(./src/functions/example-post/function.yml)}
  - ${file(./src/functions/example-get/function.yml)}

# Resources: ${file(./serverless.resources.yml)}

custom:
  serverless-offline:
    httpPort: 4000 # @NOTE: update to the service port
    noPrependStageInUrl: true
  esbuild:
    bundle: true
    platform: 'node'
    minify: ${file(./config/${opt:stage, 'development'}.json):esbuild.minify, true}
    sourcemap: ${file(./config/${opt:stage, 'development'}.json):esbuild.sourcemap, false}

plugins:
  - serverless-esbuild
  - serverless-offline
