service: lambda-typescript-template
frameworkVersion: '3'

package:
  individually: true
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  # stage: production
  stackName: lambda-typescript-template
  deploymentMethod: direct
  deploymentBucket: acema-serverless
  versionFunctions: false
  httpApi:
    cors: true
  stackName: template-service # @NOTE: update to the service name
  deploymentBucket: acema-serverless
  versionFunctions: false
   # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "dynamodb:GetItem"
  #     Resource:
  #       Fn::GetAtt:
  #         - UserTable
  #         - Arn

functions:
  - ${file(./src/functions/example-post/function.yml)}
  - ${file(./src/functions/example-get/function.yml)}

# Resources: ${file(./serverless.resources.yml)}

custom:
  serverless-offline:
    httpPort: 4000 # @NOTE: update to the service port
    noPrependStageInUrl: true
    # printOutput: true # research
  esbuild:
    bundle: true
    platform: 'node'
    minify: true # @NOTE: set to 'false' for development
    sourcemap: false # @NOTE: set to 'true' for development

plugins:
  - serverless-esbuild
  - serverless-offline
