service: lambda-typescript-template
frameworkVersion: '3'

package:
  individually: true
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stackName: production-members-service
  deploymentBucket: serverless-members
  versionFunctions: false

functions:
  - ${file(./src/functions/example-post/function.yml)}
  - ${file(./src/functions/example-get/function.yml)}

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    printOutput: true
  esbuild:
    bundle: true
    platform: 'node'
    minify: true
    sourcemap: false

plugins:
  - serverless-esbuild
  - serverless-offline
