ServiceURLSSM:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /${opt:stage}/lambda/services/${self:service}
    Type: String
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: ApiGatewayRestApi
          - .execute-api.
          - Ref: AWS::Region
          - .
          - Ref: AWS::URLSuffix
          - /${opt:stage}
