service: lambda-typescript-template
frameworkVersion: '3'

package:
  individually: true
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  deploymentBucket: serverless-gca
  profile: aws-lambda-gca
  versionFunctions: false
  environment:
    APP_VERSION: ${file(./package.json):version}
    SOME_ENV_VARIABLE: '${file(./config/${self:provider.stage}.json):resources.someValue}'
  httpApi:
    cors: true
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "dynamodb:GetItem"
  #     Resource:
  #       Fn::GetAtt:
  #         - UserTable
  #         - Arn

functions:
  - ${file(./src/functions/example-post/function.yml)}
  - ${file(./src/functions/example-get/function.yml)}

# Resources: ${file(./serverless.resources.yml)}

custom:
  serverless-offline:
    httpPort: 4000 # @NOTE: update to the service port
    noPrependStageInUrl: true
    # printOutput: true
  esbuild:
    bundle: true
    platform: 'node'
    minify: true # @NOTE: set to 'false' for development
    sourcemap: false # @NOTE: set to 'true' for development

plugins:
  - serverless-esbuild
  - serverless-offline
